#lang sicp
(define (f a b)
    (cons (m 2 a) (m 3 b))
)
(define (one x)
    (car x)
)
(define (two x)
    (cdr x)
)

(define (m x y)
    (define (dnc x)
        (- x 1)
    )
    (define (inc x)
        (+ x 1)
    )
    (cond
      ((= 0 y) 1)
      ((= 1 y) x)
      ((= 0 (remainder y 2)) (m (* x x) (/ y 2)))
      (else (* x (m x (dnc y))))
    )
)