#lang sicp
(define (* b n)
  (cond ((= 0 n) 0)
        ((= 1 n) b)
        ((even? n) (* (double b) (halve n)))
        (else (+ b (* b (- n 1))))
        )
  )
(define (even? n)
  (= (remainder n 2) 0))
(define (double x)
  (+ x x))
(define (halve x)
  (/ x 2))